### ISSUE TITLE
Detecting image

### ISSUE THREAD

**Issue by Bannigo** [UniBwTAS/apriltags_tas#2]
![Screenshot from 2021-02-22 17-33-32](https://user-images.githubusercontent.com/64646090/108738669-2980fb00-7534-11eb-99e4-a66631cd575c.png)
Hello, 
I am trying to detect Apriltag of family tag36h11 with id:0. The length of the marker is 5cm. Here is what terminal shows-:

![Screenshot from 2021-02-22 17-36-24](https://user-images.githubusercontent.com/64646090/108739098-91374600-7534-11eb-8689-a5cd3d890745.png)
It is indeed detecting the marker, but it seems the marker is being filtered out. I guess I need to change something in the config file. Can you help me out here?

**Comment by forkel** [comment]
Hi, for AprilTags without checkerboard corners you need to deactivate the option "filter_cross_corners" in dynamic reconfigure/rqt
