### ISSUE TITLE
Mismatch between image width / height

### ISSUE THREAD

**Issue by s-trinh** [UniBwTAS/apriltags_tas#3]
Hi,

https://github.com/UniBwTAS/apriltags_tas/blob/a34a93f9c396846ea1c76ccf6a71c1bd070dea27/apriltags_tas/src/apriltag_detector.cpp#L147

https://github.com/UniBwTAS/apriltags_tas/blob/a34a93f9c396846ea1c76ccf6a71c1bd070dea27/apriltags_tas/src/apriltag_detector.cpp#L149

I think it should be (see `img.size` variable about the index):

```cpp
x_range.second = std::min(x_range.second + 10, static_cast<float>(img.size[1] - 1));
```

and

```cpp
y_range.second = std::min(y_range.second + 10, static_cast<float>(img.size[0] - 1));
```

Since it should be row then column in `img.size` with OpenCV.

**Comment by UniBwTAS** [comment]
Is fixed, thanks for the hint!
