### ISSUE TITLE
Some minor potential code issues

### ISSUE THREAD

**Issue by s-trinh** [UniBwTAS/apriltags_tas#5]
https://github.com/UniBwTAS/apriltags_tas/blob/263b91545376ef8f9809da2022227fdd753d02e3/apriltags_tas/src/apriltag_detector.cpp#L136-L137

Should be something like

```cpp
        std::pair<float, float> x_range(std::numeric_limits<float>::max(), -std::numeric_limits<float>::min());
        std::pair<float, float> y_range(std::numeric_limits<float>::max(), -std::numeric_limits<float>::min());
```

since `std::numeric_limits<float>::min()` is always bigger than `0`.

https://github.com/UniBwTAS/apriltags_tas/blob/263b91545376ef8f9809da2022227fdd753d02e3/apriltags_tas/src/apriltag_detector.cpp#L163-L172

Can be refactored to

```cpp
            auto nextCornerIndex = [](const int i) {
                return (i+1) % 4;
            };
```

code would be easier to be understood using the modulo operator IMO.

In https://github.com/UniBwTAS/apriltags_tas/blob/263b91545376ef8f9809da2022227fdd753d02e3/apriltags_tas/CMakeLists.txt#L5

add

```
find_package(Ceres REQUIRED)
```

otherwise it gives the following error on my configuration:

```
/usr/bin/ld: //usr/local/lib/libceres.a(thread_pool.cc.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
apriltags_tas/apriltags_tas/CMakeFiles/apriltag_detector.dir/build.make:264: recipe for target '/catkin_ws/devel/lib/apriltags_tas/apriltag_detector' failed
make[2]: *** [/catkin_ws/devel/lib/apriltags_tas/apriltag_detector] Error 1
CMakeFiles/Makefile2:1436: recipe for target 'apriltags_tas/apriltags_tas/CMakeFiles/apriltag_detector.dir/all' failed
make[1]: *** [apriltags_tas/apriltags_tas/CMakeFiles/apriltag_detector.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j6 -l6" failed
```

**Comment by forkel** [comment]
You're right, I replaced `std::numeric_limits<float>::min()` by `std::numeric_limits<float>::lowest()` and also took up your other suggestions. Thank you!
